### ISSUE TITLE
add way to 'deprecate' kernels to keep them off the main list

### ISSUE THREAD

**Issue by invisiblek** [invisiblek/cve_tracker#13]

**Comment by fourkbomb** [comment]
The Github API returns an `updated_at` value. We could just say if a kernel hasn't been updated for x months (say 6) we automatically deprecate it.

**Comment by invisiblek** [comment]
i like it

**Comment by invisiblek** [comment]
https://github.com/invisiblek/cve_tracker/commit/89fc7740b421f751348a52f71e39f21b8251af10
