### ISSUE TITLE
add support for 'non-standard' kernel repo names

### ISSUE THREAD

**Issue by invisiblek** [invisiblek/cve_tracker#17]
those dirty motherfuckers...

CyanogenMod/hardkernel-kernel-4412
CyanogenMod/hp-kernel-tenderloin
CyanogenMod/htc-kernel-doubleshot
CyanogenMod/htc-kernel-espresso
CyanogenMod/htc-kernel-incrediblec
CyanogenMod/htc-kernel-liberty
CyanogenMod/htc-kernel-msm7227
CyanogenMod/htc-kernel-msm7x30
CyanogenMod/htc-kernel-supersonic
CyanogenMod/kernel-omap
CyanogenMod/lge-kernel-gproj
CyanogenMod/lge-kernel-iproj
CyanogenMod/lge-kernel-mako
CyanogenMod/lge-kernel-msm7x30
CyanogenMod/lge-kernel-omap4
CyanogenMod/lge-kernel-p700
CyanogenMod/lge-kernel-p880
CyanogenMod/lge-kernel-sniper
CyanogenMod/lge-kernel-star
CyanogenMod/motorola-kernel-stingray
CyanogenMod/samsung-kernel-galaxys
CyanogenMod/samsung-kernel-hercules
CyanogenMod/semc-kernel-msm7x30
CyanogenMod/sony-kernel-msm8660
CyanogenMod/sony-kernel-msm8960
CyanogenMod/sony-kernel-u8500
CyanogenMod/zte-kernel-msm7x27

**Comment by invisiblek** [comment]
this is fucking ugly....

**Comment by fourkbomb** [comment]
I'm going to go ahead and ignore cm-kernel/kernel-omap.
